### PR TITLE
Fix City Banners and Minimap for Linux

### PR DESCRIPTION
**Pull request by the-m4a**
**WHAT THIS IS**
These are the changes, as limited as I could, in order for CQUI to (potentially) function on Linux.

**WHAT CHANGED**
- Renamed (using Pascal Case) CityBannerInstances.xml and CityReligionInstances.xml in the respective CQUI Expansion folders.
- Added empty, hidden containers to CityBannerInstances.xml, CityReligionInstances.xml, and citybannermanager.xml to assist in troubleshooting that those files load, along with some comments that explain what is going on.
- More Lenses minimappanel.xml file now uses that all-lowercase name in the Expansion folders
- More Lenses lua files manually do the _Include_ call for the other ModLens files, rather than the Firaxis "include all with this name-style".
  - The manual list matches the order of includes as I observed them on my Windows install.

**HOW TESTED**
I started a GS, R&F, and Vanilla game in my Linux install running this branch of the mod.  Minimap was there and I was able to found that first city and see the banner in every case.  I didn't play beyond that first turn on the Linux install.

I would appreciate any of the Linux testers grab this branch and give it a shot.

### CODE REVIEW

**Comment by alexeyOnGitHub** [comment]
I checked out this branch on linux. unsubscribed from the original CQUI in the Steam workshop, changed the local CQUI.modinfo file (different mod name, different ID - just in case), enabled the new local mod.
waited for Steam to get the latest game update (no choice there...).

this is what I see after founding a city -

image

clicking on production icon on the city banner does not bring any dialogs.

I disabled some other mods just in case (concise UI, etc) - no changes.

**Comment by alexeyOnGitHub** [comment]
for comparison, here is what I see with the current **Workshop version of CQUI**:

image

**Comment by the-m4a** [comment]
hmm weird.  clicking on the city banner brings up nothing?  I'll check it out

**Comment by RustyD** [comment]
I've continued to play a non-expansion (base) game for about 25 (early) turns, and it seems to be working fine for me.

**Comment by the-m4a** [comment]
@alexeyOnGitHub I have no issues... will paste gif below.  You can (briefly) see the yellow dot that shows when I click on the production icon.  I tried other places on the banner and they worked as well.

From your pic, what's that icon on the canal in Rome there?
image

gif

**Comment by alexeyOnGitHub** [comment]
I disabled more plugins. one of them apparently was giving that weird icon in the middle of the city, it had a tooltip saying something like "click here for screenshot mode". 
with a bunch of other plugins removed, the icon is gone. but there is still no reaction when I click on the city top bar or on the production gear icon - neither in the city bar, nor in the bottom right corner.
here are all the log files I have from this start: https://drive.google.com/file/d/1S_KJfWAqHWkxyzEuQLoWH_IwexCisT7i/view?usp=sharing

you can also email me at alskor on gmail. I will edit this message to remove the email from this comment once you get it.

**Comment by the-m4a** [comment]
Clicked - and requested access with my gmail account.  That's just all sorts of puzzling, and I'm guessing something is broken with the other city screens?  If you look at the Firaxis files on your Linux install, are they all lower-cased?  I wonder if there's somehow differences between different flavors of linux?
(My WSL is running Ubuntu 20.04 I believe)

**Comment by alexeyOnGitHub** [comment]
I added a list of all files in the mod folder here: https://pastebin.com/6Kebr7eZ

**Comment by the-m4a** [comment]
Does it also fail for a Rise&Fall game?  The banners for RF and GS look the same, but those files do live in separate places a bit.  The banners for Vanilla have worked (as far as I know), but I'd be curious as to what's going on there as well.

The square bracket keys ( '[' and ']' ) bring up previous and next city, I wonder if those do anything?  (They _should_ bring up the city screen... just a matter of confirming that it's failing entirely to bring them up, or if somehow the registration of the mouse clicks got messed up)

**Comment by alexeyOnGitHub** [comment]
started a new game with "Rise and Fall" ruleset. same problem - clicking on the city bar or the bottom right production gear icon does nothing. same for pressing "[" or "]".
I also had a problem selecting the 1st warrior with the mouse. I was then able to select it by clicking on that small "!" icon near the bottom right corner, and then use the unit. next turn I was able to select it with the mouse directly on the map though. it is almost like the mouse mapping was fixed after the first selection.

started a new game with "standard rules"  - same exact problem: cannot select the city details or the production gear, and the same problem with selecting the warrior on the map, until I FIRST select it via "!" icon in the bottom right - then I can also select it on the map.

**Comment by alexeyOnGitHub** [comment]
we can have a zoom session with remote debugging if you are curious. I am in PST zone (San Francisco).

**Comment by RustyD** [comment]
I started a new game on Rise and Fall, and played about 45 turns. Everything seemed to be working from my point of view, apart from all the worker actions were not expanded (if they are supposed to be in RnF?)

**Comment by the-m4a** [comment]
my availability to do things is so random that I can't commit to a zoom at the moment - though if I end up with time I'd be willing.  I guess, just be absolutely sure that you have only CQUI enabled?  It's really strange...

Also Rusty - thank you!  I don't remember if the worker actions were supposed to be expanded, not sure offhand..

**Comment by alexeyOnGitHub** [comment]
I disabled "Sukritact's Simple UI adjustments" mod and now I am able to open the production panel on Linux. 
apologies for not trying this option earlier. I have disabled a bunch of other mods in my previous test runs, but that one usually "just worked", so I ignored it.

I noticed some city-related problems in my Windows Civ6 game earlier today, and disabling that mod fixed them (for Windows). 
this is what got me to try disabling it in Linux as well. 

I don't mind merging this version.

**Review by alexeyOnGitHub — APPROVED** [review]

**Comment by the-m4a** [comment]
Ah, yeah that makes sense, it gets a little tricky with the city panels and that mod and CQUI. If I remember, next time I fire up the Linux install I"ll see if I can determine what's going on.  Looking at the files that are in that mod, I'd wager that it's something like CityPanel.xml is all lower-cased in CQUI, but not in the Concise UI mod...

**Pull request merged**
