### PR TITLE
Reduce Replacement: WorldTracker

### PR DESCRIPTION
**Pull request by the-m4a**
**These changes are in the current m4a-ppe branch** -- y'all can use that branch for testing if you'd prefer to download 1 version of files instead of 5 or 6 different ones.  I'll leave the pull requests all separated, however. 

Was looking at the WorldTracker issue mentioned in #122 - in an attempt to solve compat issues with the black death scenario. Unfortunately the issues with that scenario go beyond just whatever was going on with WorldTracker, but these changes at the very least accomplish the goal of reducing the full-on replacing of files.

The version of WorldTracker that CQUI had in place was not entirely up to date with the one currently in the game.  The only things it really did was to add tool tips to the Research and Civics panels on the left side.  The changes in this file implement those tool tips and otherwise things seem to work fine.

Tested with Base, EXP1, EXP2

### CODE REVIEW

**Comment by Infixo** [comment]
@the-m4a Please see my comments in the issue #122 first.

**Review by Infixo — APPROVED** [review]
Here's my proposition.
Remove .xml - it doesn't add anything.
Leave 1 extension file that handles the tooltip.

**Comment by Infixo** [comment]
@the-m4a Please check your issue with BlackDeath scenario.

**Comment by the-m4a** [comment]
Cleaned up the modinfo conflict, thanks for the review @Infixo

**Pull request merged**
