### PR TITLE
#125: add resource and gold maintenance cost

### PR DESCRIPTION
**Pull request by Infixo**
As requested - the tooltip contains gold and resource maintenance of the unit that is going to be created.

### CODE REVIEW

**Comment by alexeyOnGitHub** [comment]
can you please paste a screenshot of the proposed popup tooltip?

**Comment by the-m4a** [comment]
I played with this a bit and like it, but also found myself wondering the costs of what I was upgrading from, so I experimented with also adding that.  The changes are significant enough that I would rather get buy-off before pushing them.

These screen shots are with my changes:
Current unit is listed first, upgraded unit second:
image
image
image
I double-checked that Nuclear subs do not consume any resources, thought they would at least take a uranium:
image
for @alexeyOnGitHub - This is what the current set of changes from Infixo looks like:
image

**Comment by the-m4a** [comment]
This is the code, I can push this up if desired.  (Lines 1-22 in the file above this remain the same):

```
-- ===========================================================================
function AddUpgradeResourceCost( pUnit:table )
    local toolTipString:string = BASE_CQUI_AddUpgradeResourceCost( pUnit );
    -- Check again if the operation can occur, this time for real.
    -- we already did that in the parent function, so it should return the same results now
    local _, tResults = UnitManager.CanStartCommand( pUnit, UnitCommandTypes.UPGRADE, false, true);

    -- add the unit it will upgrade to in the tooltip as well as the upgrade cost
    if tResults ~= nil and tResults[UnitCommandResults.UNIT_TYPE] ~= nil then
        local upgradeToUnit:table = GameInfo.Units[tResults[UnitCommandResults.UNIT_TYPE]];
        --print("AURC: proper upgrade-to unit", upgradeToUnit.UnitType, upgradeToUnit.Name);
        -- upgrade to unit name
        local currentUnit = GameInfo.Units[pUnit:GetUnitType()];
        local curUnitToolTipString = Locale.Lookup(currentUnit.Name).." [ICON_GoingTo] ";
        local upgUnitToolTipString = Locale.Lookup(upgradeToUnit.Name).." [ICON_GoingTo] ";
        -- gold
        curUnitToolTipString = curUnitToolTipString..Locale.Lookup("LOC_TOOLTIP_BASE_COST", currentUnit.Maintenance, "[ICON_Gold]", "LOC_YIELD_GOLD_NAME"); -- Base Cost: {1_Amount} {2_YieldIcon} {3_YieldName}
        upgUnitToolTipString = upgUnitToolTipString..Locale.Lookup("LOC_TOOLTIP_BASE_COST", upgradeToUnit.Maintenance, "[ICON_Gold]", "LOC_YIELD_GOLD_NAME"); -- Base Cost: {1_Amount} {2_YieldIcon} {3_YieldName}
        -- resources
        curUnitToolTipString = curUnitToolTipString..(CQUI_GetUnitResourceRequirements(currentUnit));
        upgUnitToolTipString = upgUnitToolTipString..(CQUI_GetUnitResourceRequirements(upgradeToUnit));
        -- combine into the tooltip
        local dashedlinelen = string.len(curUnitToolTipString);
        if (string.len(upgUnitToolTipString) > string.len(upgUnitToolTipString)) then
            dashedlinelen = string.len(upgUnitToolTipString);
        end

        toolTipString = toolTipString.."[NEWLINE]"..string.rep("-", dashedlinelen);
        toolTipString = toolTipString.."[NEWLINE]"..curUnitToolTipString.."[NEWLINE]"..upgUnitToolTipString;
    end -- if tResults

    return toolTipString;
end

-- ===========================================================================
function CQUI_GetUnitResourceRequirements ( pUnit:table )
    local retVal = "";
    local unitInfoXP2:table = GameInfo.Units_XP2[ pUnit.UnitType ];
    if unitInfoXP2 ~= nil and unitInfoXP2.ResourceMaintenanceType ~= nil then
        local resourceName:string = Locale.Lookup(GameInfo.Resources[ unitInfoXP2.ResourceMaintenanceType ].Name);
        local resourceIcon = "[ICON_" .. GameInfo.Resources[unitInfoXP2.ResourceMaintenanceType].ResourceType .. "]";
        retVal = " "..Locale.Lookup("LOC_UNIT_PRODUCTION_FUEL_CONSUMPTION", unitInfoXP2.ResourceMaintenanceAmount, resourceIcon, resourceName); -- Consumes: {1_Amount} {2_Icon} {3_FuelName} per turn.
    end -- unit info xp2

    return retVal;
end

```

**Comment by Infixo** [comment]
My code lists gold and resources as stated in the incident. You just took a submarine as example which is bad, because it doesn’t consume resources.

The idea is ok, just pls code it without that weird str.len check in the middle. There is no need for that.

**Comment by the-m4a** [comment]
the other pics showed what your code does as well, since it's the same code applied to current and upgraded.
the string length thing was just for the separator, so it spans the width of the tip, as I don't know there's a way to just add a "line". I can live without it, nbd.

**Comment by the-m4a** [comment]
ok, adjusted and will push the code.  this might look a bit goofy because i was still running at 1024x768
image

**Comment by alexeyOnGitHub** [comment]
I would remove the green arrow from the "current state" row. when I see a green arrow like this, I assume this is a `diff` : 
"before: X, ARROW -> , after: Y."
generally, it is common to use arrows to show the transition and not just the end state.

but in this UI there are two green arrows: the 1st one shows the old value ("before") , and the 2nd one shows the new one ("after").
I would rather have a single green arrow, with left+right sides representing "before" and "after".
or at least remove the arrow from the 1st row.

**Comment by Infixo** [comment]
Meaning of arrows is subjective.
I often use the font icons to not create labels and texts, so save time and pain of getting them translated.
I used the arrow in BRS and it means basically: this unit => has this features
So, for me it is not an "end state" but the "logical flow".

**Pull request merged**
