### PR TITLE
Linux minimap working, based on the more lenses branch

### PR DESCRIPTION
**Pull request by RustyD**
This branch contains a series of commits that show the incremental changes required to get the minimap 'working' on Linux, for both the base/standard game and the first 2 expansions.

Civ6/Lua on Linux seems to require some filenames be in lowercase, and the 'references' to those files also be in lower case.

It's also worth noting that I spent a bit of time trying similar changes in order to get the city banners working in both the expansions (city banners work in base/standard game), but didn't manage to find a winning combination.

### CODE REVIEW

**Comment by the-m4a** [comment]
totally baffling why it works in the lowercase but not uppercased when the base version of the file is uppercased
I'm okay with this - any thoughts @Infixo ?

**Comment by Infixo** [comment]
Read Wiki
https://github.com/civfanatics/CQUI_Community-Edition/wiki/File-Replacement,-Lua-Include,-Windows-and-Linux

Basically those files should be lowercased, in the first place.

What are the results with this change? Because technically it seems ok. Is it working or what?

**Comment by Infixo** [comment]
@RustyD City banners are transformed into extensions, to they should be Capitalized as in Windows.

**Comment by RustyD** [comment]
> Read Wiki
> https://github.com/civfanatics/CQUI_Community-Edition/wiki/File-Replacement,-Lua-Include,-Windows-and-Linux
> 
> Basically those files should be lowercased, in the first place.
> 
> What are the results with this change? Because technically it seems ok. Is it working?

Yes, the minimap seems to be functional with both the extra lenses and CQUI menu also available, for base/standard game and both extensions.

**Comment by Infixo** [comment]
Anyone knows why I don't see this PR in GitHub Desktop? Or what to do to test in in Windows?

**Comment by RustyD** [comment]
> Anyone knows why I don't see this PR in GitHub Desktop? Or what to do to test in in Windows?

It might because the branch is hosted in my repo, and Github Desktop doesn't show it? (that's a wild guess). If that's the case, then the branch/commits will need to be (and I'm guessing again here) merged somehow in to this repo before they become visible to you?

Unless, there are some settings in Github desktop where you can add my repo to what you are viewing? (Yet another guess).

**Comment by Infixo** [comment]
Ok, it fixed itself, I can see it now. Maybe some sort of sync problem.

**Comment by StragaSevera** [comment]
Alas, this branch does not work for me. Still no minimap.

**Comment by RustyD** [comment]
> Alas, this branch does not work for me. Still no minimap.

Did you try just the base/standard game with no other mods installed/enabled?

**Comment by Infixo** [comment]
@StragaSevera Do you have lua.log?

**Comment by the-m4a** [comment]
I've been wanting to hold off on this one because of my on-and-off trying to get Civ to work in the Windows Subsystem for Linux.  I need to bite the bullet and allow my home PC to be enrolled in the Windows insiders program so I can get the build that, in theory, should allow me to run Civ in a Linux environment.  

Right now I'm at the point where I can get Civ launched and see the Firaxis splash screen and stuff, but then it just goes to a blank grey box.  The version of Windows I am currently on limits the OpenGL support with the NVidia driver, and the 20xxx Windows builds should allow that better openGL functionality needed in order to make Civ work.

**Comment by alexeyOnGitHub** [comment]
I can try this  on  Linux if needed. I have been using Civ6 on  Windows because Civ6 does not recognize my  NVidia card in Ubuntu, and thus works very slowly there. but logs should still be useful.

**Comment by the-m4a** [comment]
... @alexeyOnGitHub do you dual-boot, have a separate system, or are you using Ubuntu and WSL and getting Civ6 to run there because if it's that last option I'm going to be quizzing you on exactly how you got it to work so I can get it going here :)

**Comment by the-m4a** [comment]
Hah, I'm amazed... I managed to get Civ to start in a WSL (Windows Subsystem for Linux) environment, with the Tuner attached to it!
It runs incredibly slow, but that it runs _at all_ is amazing.  I've been playing with trying to get this to work on and off for 2 months now.

image

(pic shows a different branch loaded, didn't include the fixes from @RustyD here -- will incorporate those in a bit or tomorrow)

**Comment by alexeyOnGitHub** [comment]
> ... @alexeyOnGitHub do you dual-boot, have a separate system, or are you using Ubuntu and WSL and getting Civ6 to run there because if it's that last option I'm going to be quizzing you on exactly how you got it to work so I can get it going here :)

my regular OS is Ubuntu, and I dual-boot into Windows 10 when I want to play Civ 6. unfortunately, the Linux version of Civ6 does not recognize my (standard) NVidia drivers, which makes the game pretty slow (my personal perception, plus the benchmarks calculated by the game itself - you can do that from the main game menu).

I recently upgraded the computer to have a Ryzen CPU with 16 physical cores (32 virtual), so I am curious to try Civ 6  on Linux again. although... I recall  Civ6 did not utilize more than 1-2 cores, if I trust Windows resource monitor. so having more cores is not likely to address the game performance issue on linux. this is likely not the problem with the game, but rather with Linux itself (and its subpar video games support).

another issue with Linux version of Civ6 is that is always lagging behind its Windows counterpart (after each DLC or patch), which makes playing it on linux not as good.

anyway, I can test certain things on linux if you want. I am more likely to boot into Windows to actually play the game for the two reasons I described though.

as far as Windows WSL goes - I evaluated it couple times (including in Q4 2020), but I rejected it as my primary development setup. I know there are workarounds like running your own XWindow manager and connecting to it, etc, but really how much value does WSL give, comparing to a VM, to go through additional setup hurdles? :) I think WSL has a great potential once it becomes a real general-availlability-kinda product. it feels like a prototype so far, at least for the use-cases that I have.
I will give it another chance once it supports running Linux GUI apps (a development enviroment like IDEA) - otherwise I don't get why I would want WSL to begin with - its WSL/linux file integration feels so awkward and broken to me...

**Comment by the-m4a** [comment]
I'm not sure it provides huge advantages over a VM - mostly in clearing that first setup hurdle, maybe?  Also wasn't sure I'd be able to get the Live Tuner connected if I'd fired up a VMWare machine -- at least when I tried this stuff initially, a Hyper-V VM wouldn't be able to use any of the GPU, I *think* VMWare would allow it, though.  This was largely a curiosity, if I could get it to work in WSL and get the FireTuner attached.

And yeah - I may get back to poking at the Linux over the next couple of days -- it seems we may have issues with the latest release and Heroes mode.  Yay Firaxis with the monthly randomization

**Comment by the-m4a** [comment]
@RustyD - I hadn't updated this branch directly, but I did manage to get a setup going where I can use the Live Tuner with a Linux Instance (using the Windows Subsystem for Linux).  I have a branch where as of right now, both the minimap and the banners work, though in both cases it's "got things working" rather than "understood why it was broken and fixed it", so I intend to keep plugging away at it.  I added some notes and stuff in the Linux Issue Tracking thread ( #203 )

**Review by the-m4a — CHANGES_REQUESTED** [review]
blocking in order for us to stay on the one single branch (m4a-linuxDec2020) which has changes that includes the current top-level branch.  if you're able to assist over there, I would greatly appreciate it!

**Comment by the-m4a** [comment]
closing this one, as I pulled the suggestions from Rusty into the m4a-linux-203 branch

**Pull request closed without merging**
