### PR TITLE
Add Inline Quests to CityState Panels

### PR DESCRIPTION
**Pull request by the-m4a**
This picks up on work done by @Swarsele , with the modifications I mentioned in the most recent post in that PR thread. 

Looks like this now:
image

Full list of changes:
- Add quest as inline text, resizing the box accordingly (Largely Swarsele's work)
- The 2nd place Suzerain now appears below the 1st place Suzerain.
- Inline Text for quest can be toggled with CQUI Settings option
- Added comments to the CityState.xml files to call out CQUI changes
- CQUI-added elements in the XML are now only referenced if they're defined in the XML (defends against another mod updating the citystates.xml and _not_ the citystates.lua)

### CODE REVIEW

**Comment by alexeyOnGitHub** [comment]
maybe make the quest font size larger? useful for big screens with high resolution. 
I like the design overall

**Review by alexeyOnGitHub — APPROVED** [review]

**Comment by the-m4a** [comment]
I'll look at bumping up to the next size, see what it looks like before completing this one.

**Comment by the-m4a** [comment]
I will push an update for this tomorrow, @alexeyOnGitHub -- contains the code to adjust the font between 8 and 14 and scale accordingly:

gif

**Comment by the-m4a** [comment]
Pushed the changes, I'll leave this here until tomorrow before completing to allow another look if you'd like to give additional feedback

**Comment by alexeyOnGitHub** [comment]
I like the proposed design. the animated GIF is very useful, thank you!

**Pull request merged**
