### PR TITLE
Update Gossip and Notification dialogs

### PR DESCRIPTION
**Pull request by the-m4a**
**These changes are in the current m4a-ppe branch** -- y'all can use that branch for testing if you'd prefer to download 1 version of files instead of 5 or 6 different ones.  I'll leave the pull requests all separated, however. 

**What this does**
Update the default notification and gossip dialogs to look like the ones currently in game, with a minor change:
- The "default" notification window is larger sized box and font (as compared to the default unmodified game).  The current unmodified version of these is just not great and puzzling as to why they use such a small font.
- The gossip (beige) window is the same as it is in current unmodified game.

**Specific File Changes**
- StatusMessagePanel.xml is updated to match the current one found in the unmodified game, save for the changes to make the notification window larger with font that matches that in the Gossip window
- StatusMessagePanel_CQUI.lua has the pieces necessary for the gossip trimming and displaying the notification messages for the civic and science boost and completion notifications

**Other Thoughts**
I tried out using various purples and blues for the Civic/Science notifications from CQUI before ultimately deciding upon using the Culture and Science icons with the plain white text.  This was mostly because I could not find a purple that I thought was really legible on that blue background - even Magenta was not great.  The Civ6_LightBlue for the research looked okay, but yeah, that purple was brutal.

The commented out NovaGossip stuff from Firaxis is fairly new and makes me think that's a thing that will be implemented at some point, so I did not think it worth the effort to try and impelement size scaling on the message box windows. 

image
image

### CODE REVIEW

**Comment by russegon** [comment]
hi, i saw the post on civfanatics and would like to try and contribute?  I created a Github account and I know some lua and can maybe code review...

**Comment by the-m4a** [comment]
wow, thank you!  I appreciate you taking a look, I think that we would need someone with write access to this repo in order to complete the merges though :/

**Comment by russegon** [comment]
Well I will do what I can

**Comment by alexeyOnGitHub** [comment]
@russegon  I would be glad to have more people onboard! my preference is to have new people perform a few reviews (or submit some PRs) first before granting WRITE access to the repo, to ensure some predictable quality level. do you think it makes sense?

**Review by Infixo — APPROVED** [review]
Working good.

**Pull request merged**
