### PR TITLE
Fixes for real housing from improvements

### PR DESCRIPTION
**Pull request by Infixo**
Fixes issues reported by @Potworny in #153 i.e. wrong housing in the city panel and city overview not showing. Both problems caused by some issues with real housing calculations. I replaced old code with my method from BRS which is way straighforward.

### CODE REVIEW

**Comment by the-m4a** [comment]
CQUI's ReplaceUIScript for CitySupport doesn't appear to work as it is right now... so putting it in that file wouldn't do much of anything.  I'm looking at it as these changes could theoretically be applied to the CityBannerManager files and things can just be all sorts of cleaned up nicely using them

**Comment by Infixo** [comment]
I am not sure what you mean. There are no changes here that affect CitySupport script.
If there is another issue then maybe open another incident and describe what the issue is.

**Comment by the-m4a** [comment]
Yep, opened #158 
CQUICommon can be used for the GetRealHousingFromImprovements, I'll fix up the issues with CitySupport.

**Comment by Infixo** [comment]
Ok, I will move them to CQUICommon.

**Comment by the-m4a** [comment]
I got it done - cleaned up CityBannerManager too
CityBannerManager looks a ton nicer, will push the changes now - so far looks good with Maya EXP1 game

**Comment by the-m4a** [comment]
@Infixo double-check my changes look ok, everything looks good that I've tested thus far

**Comment by Infixo** [comment]
> I got it done - cleaned up CityBannerManager too

Thank you. All looks good. Merging.

**Pull request merged**
