### PR TITLE
#33 SukUI tooltips in the city panel

### LINKED ISSUE #33: Investigate interoperability with Sukritact's Simple UI Adjustments
**Is your feature request related to a problem? Please describe.**
A number of folks that have subscribed to this mod also have subscribed to Sukritact's Simple UI adjustments.  The two mods do not coexist at the moment and considering Sukritact typically produces high-quality mods, I would like to see if we can make the two co-exist.

We should not integrate that mod unless we explicitly receive permission to do so.

https://steamcommunity.com/sharedfiles/filedetails/?id=939149009

**Describe the solution you'd like**
We are able to use both mods simultaneously.

**Describe alternatives you've considered**
We can mark our mod as incompatible by adding the id of the Simple UI adjustments mod to our Block list.

**Additional context**
The mods nearly work together as is, as it appears there's conflicts with the city banner (simple UI adjustments shows a tooltip on mouseover) and closing the city screen requires using the ESC key as the [X] does not seem to respond to the click.

### PR DESCRIPTION
**Pull request by Infixo**

### CODE REVIEW

**Comment by the-m4a** [comment]
I loaded this up and it works okay for Exp1 and Exp2, but there's a couple of issues with basegame...
1. For some reason the culture growth gets hidden, if I disable Sukritract's Simple UI the culture growth returns
image

2. I can't get the City Panel Overview on the left of the City Screen to show in basegame.  Shows in Exp1 and Exp2.  Only difference I could think of was the load order, so I had tried adding the following to the CQUI.modinfo, as an experiment to see if it would work, but alas, no luck - still could not get the left-panel to appear:
``
    <ImportFiles id="CQUI_CityPanel_Basegame_Delay_Load">
      
      
      <Properties>
        <LoadOrder>50</LoadOrder>
        <Context>InGame</Context>
      </Properties>
      <Items>
        <File>Assets/UI/Panels/citypanel.lua</File>
        <File>Assets/UI/Panels/citypanel.xml</File>
        <File>Assets/UI/Panels/citypaneloverview.lua</File>
        <File>Assets/UI/Panels/citypaneloverview.xml</File>
      </Items>
    </ImportFiles>
``
I had commented out the respective 4 files in the higher section (that is presumably loading with loadorder 0, since it's not specified).

Couldn't exactly figure out what was going on before needing to get some sleep.  I can look again in the morning, potentially.

**Comment by the-m4a** [comment]
Also adding: for base, exp1, and exp2 the mouse-over tooltips from Suk's Simple UI on the CityPanel showed just fine.  They are nice, for sure

**Comment by Infixo** [comment]
I changed the name of this PR to not close entire issue. Now it is just what it is - tooltips in the city panel.
I am not planning to spend much time on this topic any more as I don’t think it is a priority. People should be aware that merging 2 overlapping Ui mods will and most likely do cause some issues. Some features will work and some not.

**Comment by Infixo** [comment]
Tl:dr The 2 problems you commented are not related to the actual changes from this PR.

**Comment by the-m4a** [comment]
Thats fair.  It is a curiosity as to why it was not working - not terribly important, as I could see the cqui version of citypaneloverview being loaded (via a temporary print at the beginning of the file).

**Pull request merged**
