### PR TITLE
Show War Icon in City State Banner

### PR DESCRIPTION
**Pull request by the-m4a**
When at war with a City State, show the red crossed swords icon in the banner.

Expansions (CS without and with a Suzerain):
image
image
For comparison, not at war, Maya is Suzerain:
image

Vanilla (CS without and with a Suzerain):
image
image

**Changes**
- Added as a CQUI setting, default to enabled.
- Expansions: modified the padding and anchor settings for elements in the City Banner.
  - For the expansions, I wanted the "At War" icon to be the left-most icon.
  - This meant a standalone icon rather than using the Stack control that houses the CS Icon and CS Type icon.  In order to get things to look correct, it took some playing with the anchors and padding to get that done.
- Vanilla game, the At War icon ends up in the same spot where the Suzerain icon happens to go if you declare war on one of your Suzerain City States.  Otherwise the icon goes to the left of the Suzerain icon.
  - For whatever it's worth the Vanilla banners just look so wonky to me, but I do not think that's a thing caused by CQUI.

**Tested**
- Vanilla, EXP1, EXP2
- Declared war on CS, validated that the icon appears in the banner
- Declared war on Major Civ, validated that the at war icon appears in the banner where the Major Civ is the CS Suzerain
- Validated the icon disappears/reappears when disabling/enabling the setting
- Validated the icon shows on a game load for the CS I am at war with

### CODE REVIEW

**Comment by the-m4a** [comment]
I decided against doing the file renames with this PR in order to keep things simple.  Will do the file rename in a separate PR.

**Comment by Infixo** [comment]
Looks good, but do we really need an option parameter for every single small feature?
I imagine settings should be for “permanent” changes, like a “smart banner”. You either want CQUI banner, or a vanilla banner. Here is a situation when this icon is displayed only temporary, on a specific condition. Imho there is no need for an option here. This should be a CQUI feature: you see a war icon when at war. Plain and simple.

**Comment by the-m4a** [comment]
Eh... Alexey was a fan of options, I don't mind the options, so I put in the option.  That said, I didn't want to go wandering through Google Translate to put it for the other languages, so...

**Comment by Infixo** [comment]
...so you wanna translate or remove the option?

**Comment by the-m4a** [comment]
I can add the translations.  I will do that tonight.
Can you provide the text for Polish?
```
    <Row Tag="LOC_CQUI_SHOW_WAR_ICON_IN_CITYSTATE_BANNER" Language="en_US">
      <Text>War Icon in CityState Banner</Text>
    </Row>
    <Row Tag="LOC_CQUI_SHOW_WAR_ICON_IN_CITYSTATE_BANNER_TOOLTIP" Language="en_US">
      <Text>When at war with a City State, show the War Icon in the city banner of that city state</Text>
    </Row>
```

**Comment by the-m4a** [comment]
Added the translations.
As clicking on Google translate webpage sucks, I investigated what it would take to use a Rest API and script it.  Ended up finding that Microsoft Azure has a "Cognitive Services" resource that can be used to do translations... and as long as I stay below 2 million characters in a month it'll stay free.  I don't think it'll be a problem to stay below 2 million.

I added a Wiki page with the script (https://github.com/civfanatics/CQUI_Community-Edition/wiki/PowerShell-Script-to-get-Strings-from-Azure-Translator) - but basically it means if we want to add a new setting or some text that should be translated, it's easier to get that stuff generated.

**Review by Infixo — APPROVED** [review]
Good work all together.

**Pull request merged**
