### PR TITLE
Colors of Lenses added via MoreLenses integration can be configured

### PR DESCRIPTION
**Pull request by the-m4a**
### What this is (short summary)
- All of the colors of the lenses added by the More Lenses mod are now configurable in the CQUI settings menu

### How best to Review This or Test this
- Best thing to do: load up CQUI from this branch and give it a try
- When reviewing: Hide Whitespace Changes (settings icon on the Files Changed tab of GitHub page)

### More Details and Stuff
- Edit text boxes only allow numbers and values between 0 and 255; the sliders update when values are changed
- Sliding a slider updates the value in the edit text box
- The actual lens colors settings are only updated when "Confirm" is pressed (otherwise it was very slow because values got updated with each change in the slider, etc.)
- Once a lens color is changed in a save game, it'll stay that updated color on reload
- A lot of files changed, which includes the localization files (strings generated by the Azure translation thing-a-ma-bob)
- There is a little bit of refactoring of the ModLens files to make this work, but I think the changes are pretty straight forward
- Normalizing the names of strings to make finding the localized strings easier was done (COLOR_FOO_LENS_BAR now can expect to find LOC_HUD_FOO_LENS_BAR)
- I intend to implement these changes in MoreLenses mod itself and share with Astog
- I did this because enough folks asked and I thought it interesting challenge

**Settings menu (scrolled slightly and rest of the way)**
image
image

**Gifs taken before I added the rest of the lenses to the menu, but the behavior is still the same:**

Sliders update the preview box; can just add values directly in the text boxes, and the default button returns that lens to the usual More Lenses color.  When the setting is changed, it shows as yellow.  When the gif restarts it reverts to pink.
BuilderLensColor1
BuilderLensColor2

### CODE REVIEW

**Comment by the-m4a** [comment]
Oy... this is turning into a monster but it works so far

image

**Comment by the-m4a** [comment]
Updated the title and the text on the first post.

**Review by alexeyOnGitHub — APPROVED** [review]

**Comment by RustyD** [comment]
This is an impressive update!
I have a question: how do a specify a 'neutral' color? For example, on the 'Resources' lens, I don't tend to care too much about bonus resources, so I might not want them colored at all. Would I just set the color to 'white' or 'black'? Or is this not possible the way the feature is currently written?
I'm not sure if some people are effectively asking for 'no coloring' for some things on some lenses? (I might be wrong).
I fully appreciate it would be a lot more work to implement - I am just asking the question!  ;-)

**Comment by the-m4a** [comment]
@RustyD thanks - at the moment the best way is probably just to set the "neutral" color to black, it's the least intrusive.  I was giving some thought to adding a "disable" button to go along with the default button in order to turn a color off

For example - this is setting Black for all resources when looking with the Builder lens - the Tobacco should be the only Resource not worked in the picture
image

**Pull request merged**
